{
  "formatVersion": "1.1",
  "component": {
    "group": "com.youaji.android",
    "module": "plugin-publisher",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-publisher-1.0.1.jar",
          "url": "plugin-publisher-1.0.1.jar",
          "size": 29223,
          "sha512": "a630e4a9e56758ae25c0440b09dc2643867f1f167364152483f8cc6bbef8c65c4879c1660e8ce245a19491a233d4854f05d1dc20af67d577c3f06058b7bfe112",
          "sha256": "8c1a4398f9dabcf1486569a8e34882d54054005254ea37fe6353f7b94be0845b",
          "sha1": "efb30745bb7209f70ba2b252b5e5f330fadf45f3",
          "md5": "c97fe483dadb7257b6abe2b58b74f001"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-publisher-1.0.1.jar",
          "url": "plugin-publisher-1.0.1.jar",
          "size": 29223,
          "sha512": "a630e4a9e56758ae25c0440b09dc2643867f1f167364152483f8cc6bbef8c65c4879c1660e8ce245a19491a233d4854f05d1dc20af67d577c3f06058b7bfe112",
          "sha256": "8c1a4398f9dabcf1486569a8e34882d54054005254ea37fe6353f7b94be0845b",
          "sha1": "efb30745bb7209f70ba2b252b5e5f330fadf45f3",
          "md5": "c97fe483dadb7257b6abe2b58b74f001"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-publisher-1.0.1-javadoc.jar",
          "url": "plugin-publisher-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "2b6634428e55d4fb56bd367d7774e868c73357d23f067f93e34259244965a3e449a3d459578a804b3931fcdcdb10c8aac1c5ee2f98c49dc296c3703d3fdde197",
          "sha256": "e88b583a9f6b023cdb121bba5e764c3c288625407dddb19ab4b59bd264ebccac",
          "sha1": "0ab06c61a7aa93597ca54a87791c998f0389b6f6",
          "md5": "0f99ec3ef7931bcedaf04d2525d56844"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-publisher-1.0.1-sources.jar",
          "url": "plugin-publisher-1.0.1-sources.jar",
          "size": 5723,
          "sha512": "88d377ba820692f285cb9932c46e8c0e32449c8063c8a1fdc36c181d92d6f1225a5f9040fc4ce97e3abc60e6b23bf5c5aa8cb5cc45d65ce71b8dd90e1208aeb4",
          "sha256": "1dabbb9b64525b463a8d63fcd69053dc166225ca9e35401cd4ddea3416d6caf3",
          "sha1": "4d19658d538ef6ff2989cc2ca1083d3c3f50e8c0",
          "md5": "54014bd55a43f5c7b013f876a20ba4c3"
        }
      ]
    }
  ]
}
